#!/bin/bash

# This script creates the home directory and all associated folders and 'CMakeLists' files required for the Computer Vision course's exercises.
# Each home directory created needs to be named as an argument.

if [ $# -eq 0 ];
then
	echo " Error: no input arguments given!"
	exit 1
fi

for n in "$@"
do
	if [ -e $n ];
	then
		echo " Error: The \""$n"\" folder already exist!"
		exit 1
	fi
done

for n in "$@"
do
	mkdir $n
	cd $n
	mkdir src bin img
	echo "cmake_minimum_required(VERSION 2.8)" > "CMakeLists.txt"
	echo "project(ProjectName)" >> "CMakeLists.txt"
	echo "set(PCL_DIR \"/usr/local/pcl-1.8.0/share/pcl-1.8\")" >> "CMakeLists.txt"
	echo "message(\"\n==> Finding 3rd Party Packages\")" >> "CMakeLists.txt"
	echo "find_package(OpenCV REQUIRED)" >> "CMakeLists.txt"
	echo "find_package(PCL 1.2 REQUIRED)" >> "CMakeLists.txt"
	echo "set(CMAKE_C_FLAGS \"\${CMAKE_C_FLAGS} -Wall -W\")" >> "CMakeLists.txt"
	echo "set(CMAKE_C_FLAGS_RELEASE \"-O3\")" >> "CMakeLists.txt"
	echo "set(CMAKE_C_FLAGS_DEBUG \"-g3\")" >> "CMakeLists.txt"
	echo "set(CMAKE_CXX_FLAGS \"\${CMAKE_CXX_FLAGS} -W -Wall\")" >> "CMakeLists.txt"
	echo "set(CMAKE_CXX_FLAGS_RELEASE \"-O3\")" >> "CMakeLists.txt"
	echo "set(CMAKE_CXX_FLAGS_DEBUG \"-g3\")" >> "CMakeLists.txt"
	echo "set(BASE_DIR \${CMAKE_SOURCE_DIR})" >> "CMakeLists.txt"
	echo "set(CMAKE_RUNTIME_OUTPUT_DIRECTORY \${BASE_DIR}/bin)" >> "CMakeLists.txt"
	echo "include_directories(\${OpenCV_INCLUDE_DIR})" >> "CMakeLists.txt"
	echo "include_directories(\${PCL_INCLUDE_DIRS})" >> "CMakeLists.txt"
	echo "link_directories(\${PCL_LIBRARY_DIRS})" >> "CMakeLists.txt"
	echo "add_definitions(\${PCL_DEFINITIONS})" >> "CMakeLists.txt"
	echo "add_subdirectory(src)" >> "CMakeLists.txt"
	cd src
	echo "#add_executable(phldr phldr.cpp)" > "CMakeLists.txt"
	echo "#target_link_libraries(phldr \${OpenCV_LIBS} \${PCL_LIBRARIES})" >> "CMakeLists.txt"
	echo "#" >> "CMakeLists.txt"
	cd ../..
done
echo " Directory(ies) successfully created and populated!"