#!/bin/bash

# This script builds and compiles source files into an executable.
# This only works if ran from the base directory of the project.

if [ -f CMakeLists.txt ];
then
	mkdir -p build
	cd build
	echo " Building project..."
	cmake ..
	echo " Compiling project..."
	make
	cd ..
	while getopts ":c" opt; do
		case $opt in
			c)
			echo " Cleaning up..." >&2
			rm -rf build
			;;
		esac
	done
	echo " Done!"
else
	echo " Error: The source directory \""$PWD"\" does not appear to contain CMakeLists.txt."
fi